### PR TITLE
Capture firmware version from local devices

### PR DESCRIPTION
**Pull request by zachberger**

### CODE REVIEW

**Review by ahayworth — COMMENTED** [review]
Hey, thanks for this! Overall it looks fine, but was there a reason you removed stuff for python 3.6? I know home assistant doesn't support it anymore, but I'd rather not remove support here unless we need to.

**Comment by zachberger** [comment]
As per [PEP484](https://peps.python.org/pep-0494/) Python 3.6 is EOL'd as of last December and is not receiving updates. 

That being said, the code added still should work on Python 3.6. I can revert that part of the change. I'll let you make the decision.

**Comment by balloob** [comment]
Let's remove Python 3.6 support in a different PR and let's get this PR merged 👍

**Comment by zachberger** [comment]
Dropping Python 3.6 has been removed out of this PR

**Review by ahayworth — APPROVED** [review]
Thanks! I wasn't aware it was EOL, so with that in mind I don't really have an objection to removing support. I'll merge this and if you want to open another PR to drop that: totally fine with me.

**Pull request merged**
